Landing/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('mainpage/', include('mainpage.urls')),
    path('news/', include('news_blog.urls')),
    path('admin/', admin.site.urls),
]

mainpage/urls.py
from django.urls import include, path

from . import views

app_name = 'mainpage'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
]

news_blog/urls.py
from django.urls import path

from . import views

app_name = 'news_blog'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    path('<int:issue_id>/vote/', views.vote, name='vote'),
]

mainpage/models.py
# import datetime
# from django.db import models
# from django.utils import timezone

news_blog/models.py
import datetime
from django.db import models
from django.utils import timezone


class Issue(models.Model):
    issue_topic = models.CharField(max_length=100)
    issue_text = models.CharField(max_length=400)
    issue_author = models.CharField(max_length=100)
    issue_class = models.CharField(max_length=100)
    pub_date = models.DateTimeField('date published')

    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)

    def __str__(self):
        return self.issue_topic


class Comment(models.Model):
    issue = models.ForeignKey(Issue, on_delete=models.CASCADE)
    comment_text = models.CharField(max_length=400)
    comment_author = models.CharField(max_length=100)

    def __str__(self):
        return self.comment_text


class Image(models.Model):
    issue = models.ForeignKey(Issue, on_delete=models.CASCADE)
    issue_image = models.ImageField(null=True)


# DEBUG
# if __name__ == '__main__':
    # q = Question()

python_lessons/models.py
from django.db import models

# Create your models here.

mainpage/views.py
from django.http import HttpResponse, HttpResponseRedirect, Http404
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.views import generic

from news_blog.views import *

news_blog/views.py
from django.http import HttpResponse, HttpResponseRedirect, Http404
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.views import generic

from news_blog.models import Issue, Comment


class IndexView(generic.ListView):
    template_name = 'mainpage/index.html'
    context_object_name = 'latest_issue_list'

    def get_queryset(self):
        """Return the last five published questions."""
        return Issue.objects.order_by('-pub_date')[:5]


class DetailView(generic.DetailView):
    model = Issue
    template_name = 'news_blog/detail.html'


class ResultsView(generic.DetailView):
    model = Issue
    template_name = 'news_blog/results.html'


def vote(request, issue_id):
    issue = get_object_or_404(Issue, pk=issue_id)
    try:
        selected_issue = issue.comment_set.get(pk=request.POST['issue'])
    except(KeyError, Comment.DoesNotExist):
        return render(request, 'news_blog/detail.html', {
            'issue': issue,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_issue.comment_text = request.POST['issue']
        selected_issue.save()
        return HttpResponseRedirect(reverse('news_blog:detail', args=(issue.id,)))

python_lessons/views.py
from django.shortcuts import render

# Create your views here.

mainpage/templates/mainpage/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title%} Landing {% endblock %}</title>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'mainpage/style.css' %}">
    {%block imports%}
    {%endblock imports%}
</head>
<body>
    {% block header %}
    <header>
        <ul class="header1">
            <li class="logo"><a href="{% url 'mainpage:index' %}"><h3>LOGO</h3></a></li>
            <li class="login"><a href="#login">Login</a></li>
        </ul>
    </header>
    <ul class="banner_container">
        <li class="banner"><a href="#lt">LT</a></li>
        <li class="banner"><a href="#sql">SQL</a></li>
        <li class="banner"><a href="#python">Python</a></li>
    </ul>
    {% endblock header %}

    {% block left_aside %}

    {% endblock left_aside %}


    {% block content %}

    {% endblock content %}

    {% block footer %}
    {% endblock footer %}
</body>
</html>

mainpage/templates/mainpage/index.html
{% extends "./base.html" %}

{%block imports%}

{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'news_blog/aside_style.css' %}">
{%endblock imports %}

{% block left_aside %}
<aside class="left_aside">



    {% if latest_issue_list %}
    <p5>News</p5>
    <ul class="news_list">
        {% for issue in latest_issue_list %}
        <li><a href="{% url 'news_blog:detail' issue.id %}">{{ issue.issue_topic }}</a></li>
        {% endfor %}
    </ul>
    {% else %}
    <p>No news are available.</p>
    {% endif %}
</aside>
{% endblock left_aside %}

news_blog/templates/news_blog/detail.html
{% extends "mainpage/base.html" %}
{% block content %}
<form action="{% url 'news_blog:vote' issue.id %}" method="post">
{% csrf_token %}
<fieldset>
    <legend><h5>{{ issue.issue_topic }}</h5></legend>
    {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
        {{ issue.issue_text }}
        <input type="text" name="issue" id="issue">

<!--        <label for="issue">{{ issue.issue_text }}</label><br>-->

</fieldset>
<input type="submit" value="submit">
</form>
{% endblock content %}

news_blog/templates/news_blog/results.html
{% extends "mainpage/base.html" %}


{% block content %}

<h1>{{ issue.issue_text }}</h1>
<ul>

<!--{% for issue in issue.issue_comment_set.all %}-->
<!--    <li>{{ issue.choice_text }} &#45;&#45; {{ issue_comment.votes }} vote{{ issue_comment.votes|pluralize }}</li>-->
<!--{% endfor %}-->

</ul>
<a href="{% url 'news_blog:detail' issue.id %}">Vote again?</a>

{% endblock content %}